### ISSUE TITLE
Routing between network interfaces

### ISSUE THREAD

**Issue by LostKobrakai** [nerves-networking/vintage_net#183]
It would be great to be able to route internet access between network interfaces. E.g. sharing a wired internet connection with wlan connected devices, or using the nerves devices as hub for cellular connection once it's available.

**Comment by LostKobrakai** [comment]
It seems like `iptables` is to be prefered over iproute, which can only handle dump NATs:

> The netfilter engine provides a more flexible language for selection of packets to be transformed than that provided by the iproute2 suite and kernel routing functionality. Additionally, any NAT services provided by the netfilter engine come with the labor-saving and resource-consuming connection tracking mechanism. DNAT translates the address on an inbound packet and creates an entry in the connection tracking state table. For even modest machines, the connection tracking resource consumption should not be problematic.

http://linux-ip.net/html/nat-overview.html

Iptables on the other hand should be quite simple to setup for the use-case. 
https://filippobuletto.github.io/home-router-lte/#internet-connection

**Comment by LostKobrakai** [comment]
This seems to work for me on a firmware with iptables
```elixir
wan = "eth0"
cmd "sysctl -w net.ipv4.ip_forward=1"
cmd "iptables -t nat -A POSTROUTING -o #{wan} -j MASQUERADE
# Only needed if default for INPUT is DROP and firewall functionality is used
cmd "iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT"
```

**Comment by fhunleth** [comment]
That's pretty cool. Since it's so short, documenting it in `cookbook.md` seems sufficient for now. For some reason I was expecting this to be complicated, but I'm thrilled that it's not.

Thanks for reporting back what you found!

**Comment by LostKobrakai** [comment]
Only downside is that iptables seems not to be part of the default nerves systems right now. I'm using the docker enabled system of @mobileoverlord, which has to enable it: https://github.com/mobileoverlord/nerves_system_docker_rpi4/commit/f91f5c5ddf57539874ed8aa2df7eae3f5459b2bc#

**Comment by fhunleth** [comment]
Closing per PR #183.
