### ISSUE TITLE
Metric calculation breaking with multiple interfaces of the same type

### ISSUE THREAD

**Issue by jjcarstens** [nerves-networking/vintage_net#197]
When using a device with 2 interfaces of the same type, (in this case `eth0` and `eth1`), it fails to add the routes to the routing table because the metric calculated is the same

**error**
```
{:error, "ip: RTNETLINK answers: File exists\n"}
```

**inspected routes attempting to be added**
```
["route", "add", "default", "table", "100", "metric", "0", "via", "20.0.0.70", "dev", "eth1"]
["route", "add", "default", "table", "main", "metric", "50", "via", "20.0.0.70", "dev", "eth1"]
["route", "add", "default", "table", "101", "metric", "0", "via", "192.168.10.1", "dev", "eth0"]
["route", "add", "default", "table", "main", "metric", "50", "via", "192.168.10.1", "dev", "eth0"]
```

The metric is calculated by the [number of matching prioritizations](https://github.com/nerves-networking/vintage_net/blob/f52703f0c1e38d7f784dbe00e15e3a478c2c10ac/lib/vintage_net/interface/classification.ex#L72-L80), and in the case it is the same for both interfaces (`50`)

I think we just need to add a little more entropy into the calculation to make sure 2 interfaces of the same type are not trying to add the same metric on the main routing table

**Comment by fhunleth** [comment]
I hadn't tested this use case yet, but I suppose that it's not surprising that Linux doesn't like interfaces of the same priority. 

I implemented a simple fix in the attached PR. Would you mind trying it out?

**Comment by jjcarstens** [comment]
Actually going to tag @mobileoverlord to help test this (forgot to do that). It was his device and I just helped identify where the breakage was to write the issue
