### ISSUE TITLE
wlan connection status transition order does not match the document(?)

### ISSUE THREAD

**Issue by pojiro** [nerves-networking/vintage_net#268]
**Describe the bug**

At first, thank you for your great work.

I'm not sure this is bug.

According to the document, [connection_status()](https://hexdocs.pm/vintage_net/VintageNet.Interface.Classification.html#t:connection_status/0), normally transitions  :disconnected -> :lan -> :internet.

But my rpi3's wlan connection status log indicates :lan -> :disconnected -> :internet.

**To Reproduce**

Just set wlan config and power it up.

**Expected behavior**

connection_status() can be used for showing status with led.
So it should be show the status correctly.

I traced the interface properties, then i found ["interface", "wlan0", "lower_up"] got true as new_value, this cause set connection status :lan. And also checked the [code](https://github.com/nerves-networking/vintage_net/blob/9ad5d69ec8c1768adabf45be01e9954bd043be68/lib/vintage_net/interface/lan_connectivity_checker.ex#L59-L70) .

There is a note I also agree with.

> NOTE: Consider triggering based on whether the interface has an IP address or not.

**VintageNet Info**

Output of `VintageNet.info` (please hide any sensitive information like WiFi PSKs)

```
iex(2)> VintageNet.info
VintageNet 0.9.3

All interfaces:       ["eth0", "lo", "wlan0"]
Available interfaces: ["wlan0"]

Interface eth0
  Type: VintageNetEthernet
  Present: true
  State: :configured (0:07:01)
  Connection: :disconnected (0:06:58)
  Addresses: fe80::ba27:ebff:fe8d:e9ad/64
  Configuration:
    %{ipv4: %{method: :dhcp}, type: VintageNetEthernet}

Interface usb0
  Type: VintageNetDirect
  Present: false
  Configuration:
    %{type: VintageNetDirect}

Interface wlan0
  Type: VintageNetWiFi
  Present: true
  State: :configured (0:06:59)
  Connection: :internet (0:06:21)
  Addresses: 192.168.0.4/24, fe80::ba27:ebff:fed8:bcf8/64
  Configuration:
    %{
      ipv4: %{method: :dhcp},
      type: VintageNetWiFi,
      vintage_net_wifi: %{
        networks: [
          %{
            key_mgmt: :wpa_psk,
            mode: :infrastructure,
            psk: "....",
            ssid: "...."
          }
        ]
      }
    }
```

**Environment**

* Nerves environment: (`mix nerves.env --info`)
* Additional information about your host, target hardware or environment that might help

**Additional context**

**Comment by fhunleth** [comment]
Thanks for the report. I can confirm that this is an issue and that I'm able to reproduce it. I personally think this is a bug. I'll set aside some time in the coming weeks to dig into this more. If you learn anything more before then, please let me know.
