### ISSUE TITLE
Support hostnames for internet connectivity check

### ISSUE THREAD

**Issue by fhunleth** [nerves-networking/vintage_net#355]
Currently only IP addresses are supported and they're normally set to DNS servers. 

Frustratingly, it seems like no IP address can be guaranteed to be reachable in all places. As a workaround for this, support checking connectivity to hostnames. This would make it possible to check internet connectivity by connecting to an AWS IoT endpoint, for example.

**Comment by mattludwigs** [comment]
The `:internet_host_list` config item takes a list of tuples `{ip_address, port}` where the `ip_address` can either be a string or a tuple.

Curious as to how we differentiate between IP string or hostname string? The main reason I ask is when we check connectivity via `TCPPing.ping` we try to parse a string IP into a tuple IP. If `IP.ip_to_typle/1` fails it will give an error. Two solutions that allow us to implement this without breaking the ability to pass IPs as a string is either:

1. Match on some part of the string and make a guess as to which one the user is trying to target
2. If we cannot parse the IP we assume it is a hostname

I am not a fan of either of these as there seem to be many areas of edges that will break out best guess or if the IP is really invalid and as a user didn't mean it to be a hostname. Both are rather fragile, do you have any thoughts on this?

**Comment by fhunleth** [comment]
You can run the ip_address/name string through `:inet.gethostbyname/1`:

```elixir
iex(1)> :inet.gethostbyname('10.1.1.1')
{:ok, {:hostent, '10.1.1.1', [], :inet, 4, [{10, 1, 1, 1}]}}
iex(2)> :inet.gethostbyname('google.com')
{:ok, {:hostent, 'google.com', [], :inet, 4, [{172, 217, 15, 110}]}}
```

I would assume that calling `:inet.gethostbyname/1` with an IP address doesn't do a DNS lookup, but I don't know for sure.
