### ISSUE TITLE
Internet Connectivity Checker crash

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-networking/vintage_net#386]
debugging a remote device with no internet connectivity, so information is sparse as of yet.  From what I understand this is
a device configured via the VintageNetWizzard. 
![image](https://user-images.githubusercontent.com/21150830/154694378-72266c7b-e7aa-4bf0-b284-7add3a0b588d.png)

**Comment by fhunleth** [comment]
This is fixed in 2e35a20143f899d78101514755abf241d00f03da, but not released.
