### ISSUE TITLE
Error handling for wpa_supplicant

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-networking/vintage_net#53]
right now there is no way to tell if wpa_supplicant failed to associate with an access point, or becomes disconnected from an access point. A network that can't associate probably shouldn't be considered save to save in persistence

**Comment by fhunleth** [comment]
Couldn't the access point appear later? Like you move the device out of range and then back in range? Or the AP has a power failure and then power is restored?

**Comment by fhunleth** [comment]
You can tell if you're connected based on b72845667e07f89975cb4807cb8f84e9bd42a4ce. There seems to be a need for some kind of specialized logging, but it needs more definition. I'm going to close this for now and then when we understand the requirements we can add an issue.
