### ISSUE TITLE
DHCP Server robustness suggestion

### ISSUE THREAD

**Issue by jsimmonds2** [nerves-networking/vintage_net#55]
Playing with FarmbotOS v8.0.0 (and earlier) and found this little issue that exists when using a
Windows 10 machine to try Configurating a shiny new FarmbotOS.

Windows wants to `DHCPRELEASE` _**before**_ requesting a new address from FarmbotOS.

Am just reporting this so that this lovely 'top secret new networking library' for Nerves-based systems will be more **ROBUST** than the current Nerves_Network package :)

![image](https://user-images.githubusercontent.com/1224439/59012035-be802400-8879-11e9-9c3a-b3cbd0fe8fff.png)

**Comment by fhunleth** [comment]
Thanks. I think that FarmBot is providing their own DHCP server, since the current Nerves Networking doesn't provide one. I'm using a C-based DHCP server for `vintage_net`, so if there are problems, it won't be like the one that you're seeing.

**Comment by fhunleth** [comment]
I see. Farmbot is using this one: https://github.com/FarmBot-Labs/dhcp_server. Crashing when you release an unallocated IP address seems a little much. I don't know how long it will take for `vintage_net` to be usable in Farmbot, but you might want to file an issue over there to get it fixed sooner.

**Comment by jsimmonds2** [comment]
Many thanks for your informed comment and suggestion.   Maybe I'll just wait until `vintage_net` is ready to fly . . seems that the FarmBot team don't care much about Windows testing, so I'll keep on using Linux to Configurate :)  (I only use Windows because it works and integrates quite nicely on the Surface hardware)
