### ISSUE TITLE
Adjust internet tester?

### ISSUE THREAD

**Issue by jjcarstens** [nerves-networking/vintage_net#77]
Not really a bug, just an interesting situation I've run into.

This currently pings `1.1.1.1` (Cloudflare DNS) to test for internet connectivity. Which is fine and dandy, except that my ISP just decided to stop allowing other DNS and all my devices using vintage_net went "offline"

so just putting this here in case there are other ideas or ways to do simple connectivity checking.

Or, was also thinking to allow supplying a list of hosts to `internet_hosts` and going through each one until the next connects (similar to how DNS have fallback servers so I could supply `['1.1.1.1', '1.0.0.1']`, etc)

**Comment by fhunleth** [comment]
Yes, I think that's a really good idea. It's also possible to ask Erlang whether there are any active TCP connections to Internet-connected hosts (i.e., not on the subnet of any LAN interface) so I was hoping to take advantage of that information too.

**Comment by fhunleth** [comment]
Update: at least one school blocks DNS provider IP addresses like `1.1.1.1`, so it looks like having a list of sites to try is the way to go.
