### ISSUE TITLE
Removing WiFi dongle loops with wpa_supplicant errors

### ISSUE THREAD

**Issue by fhunleth** [nerves-networking/vintage_net#78]
**Describe the bug**
VintageNet doesn't give up retrying to configure a WiFi interface even after the WiFi dongle is removed.

**To Reproduce**
Boot with a WiFi interface with an empty configuration, remove the WiFi dongle, then hopefully you'll see this repeating in the logs:

```
23:24:00.210 [error] GenServer {VintageNet.Interface.Registry, {VintageNet.WiFi.WPASupplicant, "wlan0"}} terminating
** (MatchError) no match of right hand side value: {:error, "/tmp/vintage_net/wpa_supplicant/wlan0 not found"}
    (vintage_net) lib/vintage_net/wifi/wpa_supplicant.ex:48: VintageNet.WiFi.WPASupplicant.handle_continue/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:388: :gen_server.loop/7
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:continue, :continue}
State: %{access_points: %{}, clients: [], control_path: "/tmp/vintage_net/wpa_supplicant/wlan0", ifname: "wlan0", keep_alive_interval: 60000, ll: nil}
```

**Expected behavior**
Removing the WiFi dongle stops VintageNet from even trying to configure an interface.

**Comment by ConnorRigby** [comment]
Other ways to make this happen that I have identified:

* Switching from ap to client or client to ap
* Cause a crash in any child process of the wifi technology
