### ISSUE TITLE
Adding VintageNet does not start it as an application

### ISSUE THREAD

**Issue by Qqwy** [nerves-networking/vintage_net#89]
**Describe the bug**
Adding VintageNet as a dependency to a new RPi3-project (exactly following the steps in the README) does not start it as an application.

This makes commands like `VintageNet.info` crash with an error.

To actually start it on the Raspberry Pi I had to manually start it after starting both `:gen_state_machine` and `:muontrap`.

**Expected behavior**
It probably is expected to start up automatically when the device boots.

**Environment**

* Nerves environment: (`mix nerves.env --info`)

```
|nerves_bootstrap| Environment Package List

  No packages found
|nerves_bootstrap| Loadpaths Start


Nerves environment
  MIX_TARGET:   host
  MIX_ENV:      dev

NERVES_SYSTEM is unset
NERVES_TOOLCHAIN is unset
|nerves_bootstrap| Environment Variable List
  target:     host
  toolchain:  unset
  system:     unset
  app:        /some/directory/

|nerves_bootstrap| Loadpaths End
```

**Comment by fhunleth** [comment]
Was there anything in the logs? I'm guessing that the application started, but there was an issue that caused OTP to stop the application.

Also, can you post your example application? Suffice it to say that this isn't happening for us, so I'm guessing that we avoided it somehow and didn't think to document it.

**Comment by Qqwy** [comment]
I'll try to reproduce it in an example application :+1:

**Comment by fhunleth** [comment]
Closing old issue. A lot has changed, so please open a new issue if something similar shows up.
